### ISSUE TITLE
Consider a top-level domain for future responses

### ISSUE THREAD

**Issue by miklb** [hurricane-response/response-theme#12]
Depending on how we determine how we best serve the response, as it was brought up in Slack by @markon88 it might be better to have a single domain and use subdomains for storms.

The other part of the equation is when the storm is affecting multiple states. I've tried to address that a little bit by introducing a new collection so states can easily be added. The map element that's not necessary, but pre-storm and documenting evacuation information and resources it does.

**Comment by miklb** [comment]
This has been discussed in a multitude of places and I'm not sure there is a consensus.

@GovInTrenches @nihonjinrxs @tdooner 

Do we need to think about this still? 3 months until hurricane season officially starts.

**Comment by nihonjinrxs** [comment]
@miklb: @tdooner bought a domain for us: hurricane-response.org. I have access to modify DNS on it. So that piece is done, at least.
