### ISSUE TITLE
Analyitics

### ISSUE THREAD

**Issue by miklb** [hurricane-response/response-theme#20]
this is just a reminder to me to get with @tdooner about properly setting up analytics tools and how to differentiate between sites in the stats.

Also a reminder that we've discussed basic analytics on the API.

**Comment by carlvlewis** [comment]
You just want to set up Google Analytics, @miklb? If so, I can take care of that with segmentation by site fairly easily and share/transfer each site account to yours/whoever else's Google accounts.... 

As for API analytics, how's the current API hosted/managed? New to this project so haven't dug in that deep yet. I've used Gravitee (open-source) to manage APIs before which has basic analytics baked in: https://github.com/gravitee-io

**Comment by miklb** [comment]
Thanks! @tdooner set us up with some tracking code for Irma & tried setting up something for Michael but did something wrong. I’d like to be able to configure through the `config.yml` if possible.

As to API that might be more @nihonjinrxs territory but it’s a self hosted on Heroku. That repo is in same org

**Comment by miklb** [comment]
fixed in #27
