### ISSUE TITLE
fix positioning of search/find me on small devices

### ISSUE THREAD

**Issue by miklb** [hurricane-response/response-theme#21]
Needs a media query to position differently. I also think there is a control location that can be used instead of the method used now.

![Code For America Hurricane Response Hub-40-ms](https://user-images.githubusercontent.com/819716/58853092-0a0eb400-8667-11e9-91a9-c674d3e01359.png)

**Comment by plocket** [comment]
Switching to this bug as it seems more appropriate for now.
