### ISSUE TITLE
Improve shelter popup details - more compact, better flow

### ISSUE THREAD

**Issue by plocket** [hurricane-response/response-theme#35]
## Issue Overview

That describes it all really

**Comment by miklb** [comment]
I have pull request in that cleans up the pop up some, but I’d like to refactor the entire markup & style.

**Comment by plocket** [comment]
Making multiple items
1. Directions link should be right under address with no additional icon
1. Icons and text on same lines for anything other than 'notes'
1. Space between address/directions and other things
