### ISSUE TITLE
Visited Link Colors

### ISSUE THREAD

**Issue by miklb** [hurricane-response/response-theme#42]
## Issue Overview

some people were having issues with the visited link colors, particularly in the footer. This PR for the main site https://github.com/hurricane-response/response-hub/pull/10/commits/2af03de171b8738051f1cd0badb4ff190daab617

is an attempt to address those issues. 

These need to be tested for WCAG2AA to ensure its a fully accessible resolution.

**Comment by eloisemaun** [comment]
I'm working on this one, if you want to assign it.

**Comment by nihonjinrxs** [comment]
WCAG2AA has been tested on this, and PR is in on hurricane-response/response-hub to resolve issues found. Closing this issue in favor of a new one (#80) that consolidates/simplifies the task to be done.
