### ISSUE TITLE
Add developer docs to CONTRIBUTING.md file

### ISSUE THREAD

**Issue by nihonjinrxs** [hurricane-response/response-theme#45]
## Issue Overview

Currently, getting started working on this project is somewhat difficult for those not familar with Jekyll. We should create a `CONTRIBUTING.md` file that covers getting started in a step-by-step fashion.

## Related Issues and/or PRs

This came out of PR #23

**Comment by miklb** [comment]
fixed in c91a31e2817c1e9668a513ef3be891125caa3278
